#!/usr/bin/env python3
"""Check built HTML for dead internal links and dead in-page anchors.

    python3 tools/check-links.py _site

`mkdocs build --strict` already validates links written in the Markdown
sources. This checks the BUILT output, which covers two things it cannot:

  * the theme's own chrome and sidebar links, which are root-relative and
    generated by Jinja rather than written in a page
  * anchors after the GitHub-compatible slugify in tools/hooks.py has run

Exits non-zero, listing every failure, if anything is broken.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from urllib.parse import unquote, urldefrag

LINK = re.compile(r'(?:href|src)\s*=\s*"([^"]+)"', re.I)
ID = re.compile(r'\bid\s*=\s*"([^"]+)"', re.I)
NAME = re.compile(r'<a[^>]+\bname\s*=\s*"([^"]+)"', re.I)
EXTERNAL = re.compile(r"^(?:[a-z][a-z0-9+.-]*:|//)", re.I)


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(__doc__)
        return 2

    root = Path(argv[1]).resolve()
    if not root.is_dir():
        print(f"error: {root} is not a directory")
        return 1

    files = sorted(root.rglob("*"))
    present: set[str] = set()
    for f in files:
        if f.is_file():
            rel = "/" + f.relative_to(root).as_posix()
            present.add(rel)
            if rel.endswith("/index.html"):
                present.add(rel[: -len("index.html")])

    anchors: dict[str, set[str]] = {}
    pages = [f for f in files if f.suffix == ".html"]
    for f in pages:
        html = f.read_text(encoding="utf-8", errors="replace")
        rel = "/" + f.relative_to(root).as_posix()
        ids = set(ID.findall(html)) | set(NAME.findall(html))
        anchors[rel] = ids
        if rel.endswith("/index.html"):
            anchors[rel[: -len("index.html")]] = ids

    def resolve(page: str, target: str) -> str:
        if target.startswith("/"):
            return target
        base = page.rsplit("/", 1)[0] + "/"
        parts: list[str] = []
        for seg in (base + target).split("/"):
            if seg in ("", "."):
                continue
            if seg == "..":
                if parts:
                    parts.pop()
                continue
            parts.append(seg)
        out = "/" + "/".join(parts)
        return out + "/" if target.endswith("/") else out

    dead_links: list[str] = []
    dead_anchors: list[str] = []

    for f in pages:
        rel = "/" + f.relative_to(root).as_posix()
        html = f.read_text(encoding="utf-8", errors="replace")
        for raw in LINK.findall(html):
            raw = raw.strip()
            if not raw or EXTERNAL.match(raw):
                continue
            target, frag = urldefrag(unquote(raw))
            if not target:
                if frag and frag not in anchors.get(rel, set()):
                    dead_anchors.append(f"{rel} -> #{frag}")
                continue

            dest = resolve(rel, target)
            candidates = {dest, dest.rstrip("/") + "/", dest + "/", dest.rstrip("/")}
            if not (candidates & present):
                dead_links.append(f"{rel} -> {raw}")
                continue

            if frag:
                known = None
                for c in (dest, dest.rstrip("/") + "/", dest + "/index.html"):
                    if c in anchors:
                        known = anchors[c]
                        break
                if known is not None and frag not in known:
                    dead_anchors.append(f"{rel} -> {raw}")

    for label, items in (("dead internal links", dead_links), ("dead in-page anchors", dead_anchors)):
        print(f"{label}: {len(items)}")
        for line in sorted(set(items)):
            print(f"  {line}")

    print(f"\nchecked {len(pages)} pages")
    return 1 if dead_links or dead_anchors else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
